# Generated by Django 5.0.8 on 2025-04-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(default='I', max_length=1, null=True)),
                ('fecha_emision', models.DateTimeField(null=True)),
                ('fecha_timbrado', models.DateTimeField(null=True)),
                ('forma_pago', models.CharField(max_length=2, null=True)),
                ('uuid', models.CharField(max_length=40)),
                ('taxpayer_id', models.CharField(max_length=15)),
                ('rtaxpayer_id', models.CharField(max_length=15)),
                ('total', models.CharField(max_length=200)),
                ('codigo_status', models.CharField(blank=True, max_length=100, null=True)),
                ('es_cancelable', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('estatus_cancelacion', models.CharField(blank=True, max_length=50, null=True)),
                ('validacion_efos', models.CharField(blank=True, max_length=10, null=True)),
                ('ultima_verificacion', models.DateField(blank=True, null=True)),
                ('folio_sustitucion', models.CharField(max_length=40, null=True)),
                ('related_cfdi', models.JSONField(default=dict)),
                ('motivo', models.CharField(max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateField(null=True)),
            ],
        ),
    ]
